// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4vhd8b6gZZMC-PEl4uE5CIEcsZP3mmfc',
    appId: '1:78349546809:web:26e5969b52916dd54224e8',
    messagingSenderId: '78349546809',
    projectId: 'chelamedic-e54a1',
    authDomain: 'chelamedic-e54a1.firebaseapp.com',
    storageBucket: 'chelamedic-e54a1.firebasestorage.app',
    measurementId: 'G-FMPB39KL56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuBjjm9L7lJ1BwL71lRJEGKiHOnz8OIGA',
    appId: '1:78349546809:android:2cb578f59d868c504224e8',
    messagingSenderId: '78349546809',
    projectId: 'chelamedic-e54a1',
    storageBucket: 'chelamedic-e54a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Nuer-00yKDULm3T25aifoHWno62WGBE',
    appId: '1:78349546809:ios:09adbeb6822bea2d4224e8',
    messagingSenderId: '78349546809',
    projectId: 'chelamedic-e54a1',
    storageBucket: 'chelamedic-e54a1.firebasestorage.app',
    iosBundleId: 'com.example.chelaMedicWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Nuer-00yKDULm3T25aifoHWno62WGBE',
    appId: '1:78349546809:ios:09adbeb6822bea2d4224e8',
    messagingSenderId: '78349546809',
    projectId: 'chelamedic-e54a1',
    storageBucket: 'chelamedic-e54a1.firebasestorage.app',
    iosBundleId: 'com.example.chelaMedicWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4vhd8b6gZZMC-PEl4uE5CIEcsZP3mmfc',
    appId: '1:78349546809:web:1c9f43ccbe7de2d04224e8',
    messagingSenderId: '78349546809',
    projectId: 'chelamedic-e54a1',
    authDomain: 'chelamedic-e54a1.firebaseapp.com',
    storageBucket: 'chelamedic-e54a1.firebasestorage.app',
    measurementId: 'G-TYS771HGE2',
  );
}
